version: '2.2'
services:

# APPLICATION TIER

  web:
    build:
      context: ./
      dockerfile: docker/build/web/Dockerfile
      args:
        PHP_VERSION: 7.1
        DRUPAL_VERSION: ~8
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: tcp://10.0.2.2:1514
    #     tag: "{{.Name}}/{{.ID}}"
    cpus: 1.0
    mem_limit: 15000000000
    depends_on:
      - db
    networks:
      default:
        aliases:
          - d8.loc
          - www.d8.loc
          - es.d8.loc
          - redis.d8.loc
          - logs.d8.loc
          - s3.d8.loc
    ports:
      - "80:80"
      - "443:443"
    env_file: ./docker/env
    volumes:
      - ./status.php:/var/www/drupal/web/status.php:rw
      - ./composer.json:/var/www/drupal/composer.json:rw
      - ./config:/var/www/drupal/config:rw
      - ./sites/default/services.yml:/var/www/drupal/web/sites/default/services.yml:rw
      - ./sites/development.services.yml:/var/www/drupal/web/sites/development.services.:rw
      - ./sites/default/settings.php:/var/www/drupal/web/sites/default/settings.php:rw
      - ./sites/default/settings.dev.php:/var/www/drupal/web/sites/default/settings.dev.php:rw
      - ./sites/all/modules/custom:/var/www/drupal/web/sites/all/modules/custom:rw
      - ./sites/all/themes/custom:/var/www/drupal/web/sites/all/themes/custom:rw
      - ./sites/default/files:/var/www/drupal/web/sites/default/files:rw
      - ./docker/build/web/export_drupal_config.sh:/var/www/drupal/web/export_drupal_config.sh:rw
      - ./docker/build/web/import_drupal_config.sh:/var/www/drupal/web/import_drupal_config.sh:rw
      - ./docker/certs:/certs:ro
      - ./docker/build/web/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./docker/build/web/etc/nginx/partials:/etc/nginx/partials:rw
      - ./docker/build/web/etc/nginx/sites-enabled:/etc/nginx/sites-enabled:rw
      - ./docker/build/web/etc/php/7/fpm/php-fpm.conf:/etc/php/curr/fpm/php-fpm.conf:rw
      - ./docker/build/web/etc/php/7/fpm/pool.d/www.conf:/etc/php/curr/fpm/pool.d/www.conf:rw
      - ./docker/build/web/etc/php/7/fpm/php.ini:/etc/php/curr/fpm/php.ini:rw
      - ./docker/build/web/etc/php/7/cli/php.ini:/etc/php/curr/cli/php.ini:rw
      - ./docker/build/web/etc/services.d:/etc/services.d:rw
      - ./docker/build/web/etc/cont-init.d:/etc/cont-init.d:rw

# PERSISTANCE TIER

  db:
    image: mysql:5.7
    # logging:
    #   driver: none
    networks:
      default:
        aliases:
          - db.d8.loc
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=d8
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - ./docker/data/db:/var/lib/mysql:rw
      # - ./docker/initdb.d/:/docker-entrypoint-initdb.d/:ro
      #- ./docker/certs/ca.pem:/var/lib/mysql/ca.pem:rw
      #- ./docker/certs/db-server-cert.pem:/var/lib/mysql/db-server-cert.pem:rw
      #- ./docker/certs/db-server-key.pem:/var/lib/mysql/db-server-key.pem:rw

  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  #   logging:
  #     driver: none
  #   networks:
  #     default:
  #       aliases:
  #         - es.d8.loc
  #   ports:
  #     - "9443:9443"
  #     - "9300:9300"
  #   volumes:
  #     - ./data/elasticsearch:/usr/share/elasticsearch/data:rw
  #     - ./docker/certs:/usr/share/elasticsearch/config/x-pack/certificate-bundle:rw
  #     - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw

  s3:
    image: andrewgaul/s3proxy
    logging:
      driver: none
    ports:
      - "9000:80"
    environment:
      S3PROXY_AUTHORIZATION: none
      S3PROXY_CORS_ALLOW_ALL: "true"
      S3PROXY_IGNORE_UNKNOWN_HEADERS: "true"
    volumes:
      - ./docker/data/s3:/data:rw

  # redis:
  #   image: redis:3-alpine
  #   logging:
  #     driver: none
  #   # logging:
  #   #   driver: syslog
  #   #   options:
  #   #     syslog-address: tcp://10.0.2.2:1514
  #   #     tag: "{{.Name}}/{{.ID}}"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./data/redis:/data:rw

# LOGGING TIER

  # splunk:
  #   image: splunk/splunk:6.5.3
  #   logging:
  #     driver: none
  #   environment:
  #     SPLUNK_START_ARGS: --accept-license --answer-yes
  #     SPLUNK_ENABLE_LISTEN: 9997
  #     SPLUNK_ADD: tcp 1514
  #     SPLUNK_USER: root
  #     # SPLUNK_CMD: "edit user admin -password admin -role admin -auth admin:changeme"
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #     - "8088:8088"
  #     - "1514:1514"
  #   volumes:
  #     - ./docker/splunk/inputs.conf:/opt/splunk/etc/apps/splunk_httpinput/local/inputs.conf:rw
