version: '3'
services:
    drupal:
      build: ./docker/drupal
      env_file: ./env
      depends_on:
        - db
      networks:
        - front
      ports:
        - "9000:9000"
        - "80:80"
        - "443:443"
      volumes:
        - ./app/drupal:/var/www/local:rw
        - ./app/drupal/modules:/var/www/html/modules:rw
        - ./app/drupal/sites:/var/www/html/sites:rw
        - ./app/drupal/themes:/var/www/html/themes:rw
        - ./app/drupal/vendor:/var/www/html/vendor:rw
        - ./app/drupal/composer.json:/var/www/html/composer.json:rw
        - ./app/drupal/composer.lock:/var/www/html/composer.lock:rw

    db:
      image: mariadb:10.3
      # user: root
      # command: mysqld --skip-grant-tables
      networks:
        front:
          aliases:
            - mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=d8
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
        - MYSQL_USER=root
        - MYSQL_PASSWORD=
      volumes:
        - ./data/db:/var/lib/mysql:rw
        - ./docker/db/rootfs/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:rw

    # db:
    #   image: mysql:5.7
    #   user: root
    #   command: mysqld --skip-grant-tables
    #   networks:
    #     - front
    #   ports:
    #     - "3306:3306"
    #   environment:
    #     - MYSQL_DATABASE=d8
    #     - MYSQL_ALLOW_EMPTY_PASSWORD=1
    #     - MYSQL_USER=root
    #     - MYSQL_PASSWORD=
    #   volumes:
    #     - ./data/db:/var/lib/mysql:rw
    #     - ./docker/db/rootfs/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:rw

networks:
    front:
