version: '3'
services:
    drupal:
      build:
        context: ./docker/drupal
        dockerfile: Dockerfile
      env_file: ./env
      depends_on:
        - db
      networks:
        - front
      ports:
        - "80:8080"
        - "443:8443"
      volumes:
        - ./app/drupal:/var/www/local:rw
        - ./app/drupal/composer.json:/var/www/drupal/composer.json:rw
        - ./app/drupal/web/sites/development.services.yml:/var/www/drupal/web/sites/development.services.yml:rw
        - ./app/drupal/web/sites/default/settings.php:/var/www/drupal/web/sites/default/settings.php:rw
        - ./app/drupal/web/sites/default/settings.local.php:/var/www/drupal/web/sites/default/settings.local.php:rw
        - ./app/drupal/web/sites/default/files:/var/www/d8/web/sites/default/files:rw
        - ./app/drupal/web/modules/custom:/var/www/drupal/web/modules/custom:rw
        - ./app/drupal/web/themes/custom:/var/www/drupal/web/themes/custom:rw
        - ./app/drupal/web/libraries:/var/www/drupal/web/libraries:rw
        - ./app/drupal/config:/var/www/drupal/config:rw

    db:
      image: mariadb:10.3
      # user: root
      # command: mysqld --skip-grant-tables
      networks:
        front:
          aliases:
            - mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=d8
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
        - MYSQL_USER=root
        - MYSQL_PASSWORD=
      volumes:
        - ./data/db:/var/lib/mysql:rw
        - ./docker/db/rootfs/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:rw

    # db:
    #   image: mysql:5.7
    #   user: root
    #   command: mysqld --skip-grant-tables
    #   networks:
    #     - front
    #   ports:
    #     - "3306:3306"
    #   environment:
    #     - MYSQL_DATABASE=d8
    #     - MYSQL_ALLOW_EMPTY_PASSWORD=1
    #     - MYSQL_USER=root
    #     - MYSQL_PASSWORD=
    #   volumes:
    #     - ./data/db:/var/lib/mysql:rw
    #     - ./docker/db/rootfs/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:rw

networks:
    front:
