channels:
  -
    id: purgers
    grants:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: diagnostics
    grants:
      - 3
  -
    id: purger_cloudfront_f53ca97b06
    grants:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
  -
    id: purger_akamai_335883f48e
    grants:
      - 0
      - 2
      - 3
