cluster.name: "docker-cluster"
network.host: 0.0.0.0
http.port: 9443

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

#xpack.ssl.key:                        /usr/share/elasticsearch/config/x-pack/certificate-bundle/elasticsearch/elasticsearch.key
#xpack.ssl.certificate:                /usr/share/elasticsearch/config/x-pack/certificate-bundle/elasticsearch/elasticsearch.crt
#xpack.ssl.certificate_authorities: [ "/usr/share/elasticsearch/config/x-pack/certificate-bundle/ca/ca.crt" ]

xpack.ssl.key:                        /usr/share/elasticsearch/config/x-pack/certificate-bundle/es-server-key.pem
xpack.ssl.certificate:                /usr/share/elasticsearch/config/x-pack/certificate-bundle/es-server-cert.pem
xpack.ssl.certificate_authorities: [ "/usr/share/elasticsearch/config/x-pack/certificate-bundle/ca.pem" ]
xpack.security.http.ssl.enabled: true

# xpack.security.enabled: false
#xpack.security.transport.ssl.enabled: true
xpack.security.authc:
  anonymous:
    username: anonymous_user
    roles: superuser
    authz_exception: true

cluster.routing.allocation.disk.watermark.high: "99%"
cluster.info.update.interval: "10m"
