<?php

/**
 * @file
 * Contains file_downloader.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function file_downloader_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the file_downloader module.
    case 'help.page.file_downloader':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Example File Downloader') . '</p>';
      return $output;

    default:
  }
}