<?php

/**
 * @file
 * Contains helloworld.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function helloworld_form_node_article_form_alter( &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id )
{
    $form['options']['#open'] = TRUE;

    $user = \Drupal::currentUser();
    if ( $user->hasPermission('administer site configuration') )
    {
        $form['options']['#access'] = FALSE;
    }
}

/**
 * Implements hook_help().
 */
function helloworld_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the helloworld module.
    case 'help.page.helloworld':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DanModule') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function helloworld_theme() {
  return [
    'helloworld' => [
      'render element' => 'children',
    ],
  ];
}
