access_key: access_key
secret_key: secret_key
use_instance_profile: false
default_cache_config: ''
bucket: drupal
region: us-east-1
use_cname: false
use_customhost: true
hostname: s3.usa.loc
domain: ''
cache_control_header: ''
encryption: ''
use_https: false
ignore_cache: true
redirect_styles_ttl: 0
no_rewrite_cssjs: false
root_folder: ''
public_folder: s3fs-public
private_folder: s3fs-private
presigned_urls: ''
saveas: ''
torrents: ''
_core:
  default_config_hash: Wz6PTtS3IfcQyIXd6y39R1bfFrylxlagWJxgMdChsCY
